export { NotFound } from './notFound'
export { MainPage } from './mainPage'
export { Auth } from './auth'
export { Catalogue } from './catalogue'
export { Basket } from './basket'
export { Selected } from './selected'
